### ISSUE TITLE
Is there a Initializing and Updating API?

### ISSUE THREAD

**Issue by KirisakiAria** [AppGalleryConnect/agc-flutter-plugin#1]
Hello!

Accourding to [https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/appgallerykit-devguide](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/appgallerykit-devguide)

If I use Huawei IAP, I must also use Initializing the App API and Updating API. But I did not find the relevant code in this repository. Will you provide this in the future?

**Comment by Mayism** [comment]
hi, @KirisakiAria If you want to use Initializing the App API and Updating API in Huawei IAP,you can clone this repositories and find the sample code in src\main\java\com\huawei\hms\game\MainActivity.java.

**Comment by KirisakiAria** [comment]
@Mayism 您好

请问下我在这个仓库的代码里找到的MainActivity.java，里面只有几行：
`package com.huawei.agconnectauthdemo;

import io.flutter.embedding.android.FlutterActivity;

public class MainActivity extends FlutterActivity {
}`
复制简单的这段就可以了吗？

**Comment by Mayism** [comment]
@KirisakiAria 不好意思 我忘记附上仓库地址了 你说的IAP的初始化和升级接口和agc-flutter-plugin这个仓库关系不大 初始化和升级接口的使用请参考[hms-game-demo](https://github.com/HMS-Core/hms-game-demo)，代码也是在src\main\java\com\huawei\hms\game\MainActivity.java文件中

**Comment by KirisakiAria** [comment]
@Mayism 谢谢您的回复。还想请问一下这段代码应该如何嵌入到flutter项目中，要把相关代码提取出来放在   
flutter项目\android\app\src\main\java\com\公司名\项目名\MainActivity.java这个文件里吗？

**Comment by Mayism** [comment]
@KirisakiAria 不好意思 当前你说的联运的初始化和更新的接口 暂时还未集成并发布flutter插件的版本 这个需求我都这边也从开发者那边有收集到 目前需求处于规划阶段 您可以继续关注下[官方文档](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/appgallerykit-devguide)，以便上线时可以及时使用

**Comment by KirisakiAria** [comment]
@Mayism 了解了 谢谢！
