### ISSUE TITLE
请提示在qq和tim里提示打开浏览器,现在新版本qq和tim已经禁止了应用内下载

### ISSUE THREAD

**Issue by zhangruiyu** [AppGalleryConnect/agc-flutter-plugin#4]
请提示在qq和tim里提示打开浏览器,现在新版本qq和tim已经禁止了应用内下载

**Comment by zhangruiyu** [comment]
提示让复制下载链接到浏览器下载,但是复制到浏览器后会给深度链接参数覆盖导致获取不到参数

**Comment by zhangruiyu** [comment]
@Mayism Mayism

**Comment by Mayism** [comment]
@zhangruiyu 您好 首先对于部分应用，确实禁止了下载和直接跳转，需要通过系统浏览器打开并且中转，该操作在应用内已经有充分的提示，另外，不会有浏览器打开获取不到参数的问题，出现这个问题后请检查您的链接配置

**Comment by zhangruiyu** [comment]
已解决忘了关闭
