### ISSUE TITLE
Exception when using the buildShortAppLinking

### ISSUE THREAD

**Issue by akfrancisco** [AppGalleryConnect/agc-flutter-plugin#5]
**__AGCAppLinking.buildLongAppLinking_** works fine.

**_AGCAppLinking.buildShortAppLinking_** builder throws the ff. error
`E/AGCAppLinkingException(27918): (PluginException) UNKNOWN: url is null`

**Comment by yycccc91** [comment]
Please check your agconnect-services.json file. Make sure you have selected your storage location in the portal and redownload this file. Also, make sure it is in the right place.

**Comment by akfrancisco** [comment]
> Please check your agconnect-services.json file. Make sure you have selected your storage location in the portal and redownload this file. Also, make sure it is in the right place.

Solution was **NOT** the agconnect-services.json file.

solution was adding a whitelist url in the app gallery app linking api.
